# Generated by Django 3.1.7 on 2021-04-06 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_uid', models.IntegerField()),
                ('ticket_title', models.CharField(max_length=1000)),
                ('ticket_content', models.TextField(max_length=2000)),
                ('ticket_file', models.FileField(upload_to='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
