# Generated by Django 3.1.7 on 2021-05-03 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientticket', '0005_auto_20210421_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientemail', models.CharField(max_length=1000)),
                ('ticket_title', models.CharField(max_length=500)),
                ('ticket_content', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
